apiVersion: v1
kind: Service
metadata:
  name: codis-server10-1
  labels:
    service: codis-server10-1
spec:
  type: NodePort
  ports:
    - port: 6900
      targetPort: 6900
      nodePort: 30087
  selector:
    name: codis-server8-1
